baseURL: "https://jiming-chen.github.io/"
title: Jiming Chen
pagination.pagerSize: 5
theme: PaperMod

enableRobotsTXT: true
enableEmoji: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Jiming Chen
  description: "Jiming Chen's Personal Website"
  keywords: [Blog, Portfolio, PaperMod]
  author: Jiming Chen
  # author: ["Me", "You"] # multiple authors
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  googleAnalytics: "G-KTD621L9T6"

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  math: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/icons/favicon.ico"
    favicon16x16: "/icons/favicon-16x16.png"
    favicon32x32: "/icons/favicon-32x32.png"
    apple_touch_icon: "/icons/apple-touch-icon.png"
    safari_pinned_tab: "</icons/apple-touch-icon.png>"

  label:
    text: "Home"
    icon: /icons/apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Jiming Chen
    subtitle: I am studying Computer Science at Cornell University. I am interested in mathematics, programming languages, and hardware design.
    imageUrl: "/headshot1.png"
    imageWidth: 200
    imageHeight: 200
    imageTitle: Jiming Chen Headshot
    buttons:

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/jjc256"
    - name: linkedin
      url: "https://www.linkedin.com/in/jiming-chen/"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

  email: "jc3759@cornell.edu"
menu:
  main:
    - identifier: About Me
      name: About Me
      url: /about
      weight: 10
    - identifier: Portfolio
      name: Portfolio
      url: /projects/
      weight: 20
    - identifier: Blog
      name: Blog
      url: /posts/
      weight: 30
    - identifier: Course Notes
      name: Course Notes
      url: /courses/
      weight: 40
    - identifier: Piano
      name: Piano
      url: /piano/
      weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
  goldmark:
    renderer:
      unsafe: true